-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 17:38:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ALUNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ALUNO` ;

CREATE TABLE IF NOT EXISTS `ALUNO` (
  `CPF` TINYTEXT NOT NULL,
  `Nome` TINYTEXT NULL,
  `Sobrenome` TINYTEXT NULL,
  `Sexo` CHAR(1) NULL,
  `DataNasc` FLOAT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALUNO_has_CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ALUNO_has_CURSO` ;

CREATE TABLE IF NOT EXISTS `ALUNO_has_CURSO` (
  `ALUNO_CPF` TINYTEXT NOT NULL,
  `CURSO_Sigla` TINYTEXT NOT NULL,
  `Data` FLOAT NULL,
  `Pago` BIT(1) NULL,
  PRIMARY KEY (`ALUNO_CPF`, `CURSO_Sigla`),
  CONSTRAINT `fk_ALUNO_has_CURSO_ALUNO1`
    FOREIGN KEY (`ALUNO_CPF`)
    REFERENCES `ALUNO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_has_CURSO_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ALUNO_has_CURSO_CURSO1_idx` ON `ALUNO_has_CURSO` (`CURSO_Sigla` ASC) VISIBLE;

CREATE INDEX `fk_ALUNO_has_CURSO_ALUNO1_idx` ON `ALUNO_has_CURSO` (`ALUNO_CPF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AREA` ;

CREATE TABLE IF NOT EXISTS `AREA` (
  `Sigla` TINYTEXT NOT NULL,
  `Nome` TINYTEXT NULL,
  `AREA_Sigla` TINYTEXT NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_AREA_AREA1`
    FOREIGN KEY (`AREA_Sigla`)
    REFERENCES `AREA` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AREA_AREA1_idx` ON `AREA` (`AREA_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CURSO` ;

CREATE TABLE IF NOT EXISTS `CURSO` (
  `Sigla` TINYTEXT NOT NULL,
  `Nome` TINYTEXT NULL,
  `Horas` INT NULL,
  `Custo` FLOAT NULL,
  `AREA_Sigla` TINYTEXT NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_CURSO_AREA1`
    FOREIGN KEY (`AREA_Sigla`)
    REFERENCES `AREA` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CURSO_AREA1_idx` ON `CURSO` (`AREA_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MODULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MODULO` ;

CREATE TABLE IF NOT EXISTS `MODULO` (
  `Sigla` TINYTEXT NOT NULL,
  `Nome` TINYTEXT NULL,
  `CURSO_Sigla` TINYTEXT NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_MODULO_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MODULO_CURSO1_idx` ON `MODULO` (`CURSO_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PROFESSOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFESSOR` ;

CREATE TABLE IF NOT EXISTS `PROFESSOR` (
  `CPF` TINYTEXT NOT NULL,
  `Nome` TINYTEXT NULL,
  `CURSO_Sigla` TINYTEXT NOT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_PROFESSOR_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PROFESSOR_CURSO1_idx` ON `PROFESSOR` (`CURSO_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TOPICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TOPICO` ;

CREATE TABLE IF NOT EXISTS `TOPICO` (
  `Sigla` TINYTEXT NOT NULL,
  `Nome` TINYTEXT NULL,
  `Horas` INT NULL,
  `MODULO_Sigla` TINYTEXT NOT NULL,
  PRIMARY KEY (`Sigla`, `MODULO_Sigla`),
  CONSTRAINT `fk_TOPICO_MODULO1`
    FOREIGN KEY (`MODULO_Sigla`)
    REFERENCES `MODULO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TOPICO_MODULO1_idx` ON `TOPICO` (`MODULO_Sigla` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
